/** Definições compartilhadas dos grupos Master, Gerente, SDR e Closer. */

export const ACCESS_GROUP_DEFINITIONS = [
  {
    code: "master",
    name: "Master",
    permissions: [
      "platform.users.manage",
      "platform.users.status",
      "platform.audit.read",
      "platform.organization.manage",
      "reports.view",
      "reports.export",
      "reports.crm.view",
      "reports.support.view",
      "reports.learning.view",
      "reports.one_on_one.view",
      "support.view",
      "learning.course.create",
      "learning.course.publish",
      "learning.enrollment.manage",
      "learning.assessment.results.view_all",
      "learning.certificate.issue",
      "gamification.view_all",
      "gamification.campaign.create",
      "gamification.campaign.publish",
      "gamification.campaign.pause",
      "gamification.campaign.close",
      "gamification.campaign.edit",
      "gamification.mission.manage",
      "gamification.points.adjust",
      "gamification.audit.view",
      "gamification.export",
      "support.ticket.manage_all",
      "support.ticket.archive",
      "support.ticket.assign",
      "support.ticket.move_team",
      "support.ticket.move_all",
      "support.ticket.block",
      "support.ticket.resolve",
      "support.board.configure",
      "support.settings.manage",
      "news.manage",
      "one_on_one.view",
      "one_on_one.meeting.manage",
    ],
  },
  {
    code: "gerente",
    name: "Gerente",
    permissions: [
      "platform.users.status",
      "support.view",
      "support.ticket.create",
      "support.ticket.move_own",
      "support.ticket.manage_all",
      "support.ticket.archive",
      "support.ticket.assign",
      "support.ticket.move_team",
      "support.ticket.move_all",
      "support.ticket.block",
      "support.ticket.resolve",
      "support.board.configure",
      "support.settings.manage",
      "one_on_one.view",
      "one_on_one.team.view",
      "one_on_one.meeting.manage",
      "learning.catalog.read",
      "learning.progress.read_team",
      "learning.course.publish",
      "learning.enrollment.manage",
      "learning.team.read",
      "learning.assessment.results.view_team",
      "gamification.view_team",
      "gamification.ranking.view",
      "gamification.missions.view",
      "gamification.campaign.publish",
      "gamification.campaign.pause",
      "gamification.campaign.close",
      "gamification.campaign.edit",
      "gamification.mission.manage",
    ],
  },
  {
    code: "sdr",
    name: "SDR",
    permissions: [
      "support.view",
      "support.ticket.create",
      "support.ticket.move_own",
      "one_on_one.view",
      "learning.catalog.read",
      "learning.progress.read_own",
      "gamification.view_own",
      "gamification.ranking.view",
      "gamification.missions.view",
      "gamification.achievements.view",
    ],
  },
  {
    code: "closer",
    name: "Closer",
    permissions: [
      "support.view",
      "support.ticket.create",
      "support.ticket.move_own",
      "one_on_one.view",
      "learning.catalog.read",
      "learning.progress.read_own",
      "gamification.view_own",
      "gamification.ranking.view",
      "gamification.missions.view",
      "gamification.achievements.view",
    ],
  },
] as const;
